baseURL = "https://thisplatypus.github.io"
languageCode = "en-US"
title = "Split - HTML Template Demo"
disableKinds = ["section", "taxonomy", "term", "rss", "sitemap"]

# Local preview mode
relativeURLs = true
uglyURLs = true

# Copyright
copyright = "&copy;2024 Your Name"

[params]
  # Metadata for search engines and social sharing
  author = "Jenny Jones"
  description = "Split is a centrally-divided layout for a professional online presence with a big image or video left with alongside content."
  shareImage = "images/social.jpg"
  twitterHandle = "onepagelove"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/background.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Header 1"

      [[params.links.list1.link]]
        text = "OtherPage"
        url = "long-text"
        new_tab = true # new tab

  
